server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev
    gateway:
      discovery:
        locator:
          enabled: true
        # 允许网关通过服务发现组件，找到其他的微服务
      routes:
        - id: route-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: route-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
            allow-credentials: 'true'
            max-age: '3600'