GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3Mjk4NTcwOTMsInBob25lIjoiMTg4NTE2ODM1NzYiLCJpZCI6MSwiZXhwIjoxNzI5ODU3MTQxLCJpYXQiOjE3Mjk4NTcwOTN9.MpLkOnb0wA_Ltm0qz5sk-upPcON3AKQWv67knfcLlCw

#{{token}}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "13951905172",
  "password": "123123"
}

> {%
    client.global.set("token",response.body.data.token);
 %}
###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone": "13951905172",
  "password": "123456"
}

###
GET http://localhost:8000/content-service/share/notice
Accept: application/json

###
GET http://localhost:8000/content-service/share/list?pageNo=3&pageSize=2
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/content-service/share/1
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/user-service/user/updateBonus
Content-Type: application/json
token:{{token}}

{
  "userId": 1,
  "bonus": 10
}

###
POST http://localhost:8000/content-service/share/exchange
Content-Type: application/json
token:{{token}}

{
  "userId": 2,
  "shareId": 8
}

###
POST http://localhost:8000/content-service/share/contribute
Content-Type: application/json
token:{{token}}

{
  "userId": 1,
  "author": "尤雨溪",
  "title": "详解 Vue.js 3",
  "isOriginal": 1,
  "price": 20,
  "downloadUrl": "http://cn.vuejs.org/",
  "cover": "http://niit-soft.oss-cn-hangzhou.aliyuncs.com/share-app/vue3.jpg",
  "summary": "详解 Vue.js 3,详解 Vue.js 3,详解 Vue.js 3,详解 Vue.js 3"
}

###
GET http://localhost:8000/content-service/share/myContribute?pageNo=2&pageSize=1
Content-Type: application/json
token: {{token}}

###
GET http://localhost:8000/content-service/share/admin/list
Content-Type: application/json
token: {{token}}