spring:
  profiles:
    active: dev

server:
  port: ${gateway-service.port}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
      web:
        exposure:
          include:
            - info
            - gateway
