spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_service?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 121.199.27.54:9876
  producer:
    group: review_group
  consumer:
    group: points_group