spring:
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        port: ${sentinel.transport.port.order-service}
        dashboard: ${sentinel.transport.dashboard}

server:
  port: ${order-service.port}
#ssy:
#  username: 松山院
#  site: www.ssy.top