server:
  port: 8081

# ????? Spring?Boot Admin Server
spring:
  boot:
    admin:
      client:
        url: http://localhost:8088

# ??????

management:
  endpoints:
    web:
      exposure:
        include: '*'
  # ?? env ???????
  info:
    env:
      enabled: true
logging:
  file:
    name: ./logs/sba-client.log
